apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
  namespace: sebastiankr
spec:
  schedule: '* * * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: busybox:latest
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - date; echo Hello from the Cluster
          restartPolicy: OnFailure
