apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-claim-name
  namespace: sebastiankr
spec:
  #storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
