apiVersion: v1
kind: Service
metadata:
  name: my-caddy-service
  namespace: sebastiankr
spec:
  selector:
    app: caddy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
