apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: sebastiankr
  name: pod-all-ro
rules:
  - apiGroups: [''] # "" indicates the core API group
    resources: ['pods']
    verbs: ['get', 'watch', 'list']
