apiVersion: batch/v1
kind: Job						
metadata:
  name: hello-job					
spec:
  template:
    metadata:
      name: hello-job			
    spec:
      containers:
      - name: hello-job-container 
        image: busybox:1.28		
        command:
        - echo					
        - "Hello, Job completed"
      restartPolicy: Never			
  backoffLimit: 4				
